[project]
id = "highline"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true
